### ISSUE TITLE
Task-Selector: Inkonsistente Abstürze

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1421]
Wenn ich den Dungeon mit `./gradlew clean :dungeon:runStarter` starte und das DNG-File `dungeon/doc/dsl/examplescripts/example_scenario.dng` auswähle und dann den Task "config" starte, gelange ich in ca. 60% der Starts in das Level und kann dort etwas machen. In ca. 40% der Fälle stürzt der Dungeon ab:

```
> Task :dungeon:runStarter
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "core.Component.getClass()" because "component" is null
        at core.Entity.add(Entity.java:79)
        at dslinterop.dslnativefunction.NativeInstantiateNamed.call(NativeInstantiateNamed.java:94)
        at dsl.interpreter.DSLInterpreter.callCallable(DSLInterpreter.java:1382)
        at dsl.interpreter.DSLInterpreter.visit(DSLInterpreter.java:798)
        at dsl.parser.ast.FuncCallNode.accept(FuncCallNode.java:52)
        at dsl.interpreter.DSLInterpreter.visit(DSLInterpreter.java:999)
        at dsl.parser.ast.AssignmentNode.accept(AssignmentNode.java:10)
        at dsl.interpreter.DSLInterpreter.executeUserDefinedFunctionBody(DSLInterpreter.java:1583)
        at dsl.interpreter.DSLInterpreter.executeUserDefinedFunctionRawParameters(DSLInterpreter.java:1453)
        at dsl.interpreter.DSLInterpreter.callCallableRawParameters(DSLInterpreter.java:1435)
        at dsl.interpreter.DSLInterpreter.buildTask(DSLInterpreter.java:351)
        at graph.TaskGraphConverter.lambda$callTaskBuilderFor$1(TaskGraphConverter.java:65)
        at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1085)
        at graph.TaskGraphConverter.callTaskBuilderFor(TaskGraphConverter.java:62)
        at graph.TaskGraphConverter.convert(TaskGraphConverter.java:47)
        at starter.Starter.lambda$onEntryPointSelection$10(Starter.java:164)
        at core.game.GameLoop.frame(GameLoop.java:190)
        at core.game.GameLoop.render(GameLoop.java:152)
        at com.badlogic.gdx.Game.render(Game.java:48)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:193)
        at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:167)
        at core.game.GameLoop.run(GameLoop.java:101)
        at core.Game.run(Game.java:56)
        at starter.Starter.main(Starter.java:128)
```

**Comment by AMatutat** [comment]
<img width="305" alt="image" src="https://github.com/Dungeon-CampusMinden/Dungeon/assets/32962412/194fb8f8-c22d-4195-8b36-09ad1d5af29a">


o_0


Ich les da viel DSL im StrackTrace..... @malt-r 

Kann es sein, dass das DNG File Buggy ist?

**Comment by cagix** [comment]
> <img alt="image" width="305" src="https://private-user-images.githubusercontent.com/32962412/305922141-194fb8f8-c22d-4195-8b36-09ad1d5af29a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzNDAwMzEsIm5iZiI6MTcwODMzOTczMSwicGF0aCI6Ii8zMjk2MjQxMi8zMDU5MjIxNDEtMTk0ZmI4ZjgtYzIyZC00MTk1LThiMzYtMDlhZDFkNWFmMjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDEwNDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNDFiMmE5YTExMGU5NDFhZWQxODY4MGNhMGYxMWVmMmI2ZmQxMzA4NGE2NWQ2MzFiYzkxMjgzM2ZmMDkzMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g8qwq8kP-yYIGUaz3tVxeSH4Z9XoZpjDcYRy1x3huyc">
> o_0
> 
> Ich les da viel DSL im StrackTrace..... @malt-r
> 
> Kann es sein, dass das DNG File Buggy ist?

@AMatutat Ja, das wird über die DSL getriggert, kommt aus aus irgendeiner nicht näher genannten Component. Möglicherweise hängt das aber auch einfach nur mit der Auflösung der Texturen über die Gradle-Subprojekte hinweg zusammen, die irgendwie immer noch nicht wirklich funktioniert (#1426) - möglicherweise aber auch nicht :)

**Comment by cagix** [comment]
So, der Zauber hat sich aufgelöst, seitdem das Auflösen der Texturen über die Gradle-Konfiguration klappt (#1443). Damit kann hier zu.
